<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Common\CommonLibraries\Common.Messaging.Abstractions\Common.Messaging.Abstractions.csproj" />
    <ProjectReference Include="..\..\..\Common\CommonLibraries\Common.Messaging.Async\Common.Messaging.Async.csproj" />
    <ProjectReference Include="..\..\..\Common\CommonLibraries\Common.Results\Common.Results.csproj" />
    <ProjectReference Include="..\Inventory.Domain\Inventory.Domain.csproj" />
  </ItemGroup>

</Project>
