<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Common.Persistence.Concurrency\Common.Persistence.Concurrency.csproj" />
    <ProjectReference Include="..\Common.Persistence.Transactions\Common.Persistence.Transactions.csproj" />
  </ItemGroup>
</Project>
