<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Common.Messaging.Outbox.Contracts\Common.Messaging.Outbox.Contracts.csproj" />
  </ItemGroup>
</Project>
