<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Common.Persistence.EntityFrameworkCore\Common.Persistence.EntityFrameworkCore.csproj" />
  </ItemGroup>
</Project>
