<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\..\Common\Foundation\Common.Optional\Common.Optional.csproj" />
    <ProjectReference Include="..\..\..\Common\Messaging\Common.Messaging.Abstractions\Common.Messaging.Abstractions.csproj" />
    <ProjectReference Include="..\..\..\Common\Messaging\Common.Messaging.Async\Common.Messaging.Async.csproj" />
    <ProjectReference Include="..\..\..\Common\Pagination\Common.Pagination\Common.Pagination.csproj" />
    <ProjectReference Include="..\..\..\Common\Persistence\Common.Persistence.Concurrency\Common.Persistence.Concurrency.csproj" />
    <ProjectReference Include="..\..\..\Common\Persistence\Common.Persistence.Resilience\Common.Persistence.Resilience.csproj" />
    <ProjectReference Include="..\..\..\Common\Persistence\Common.Persistence.Transactions\Common.Persistence.Transactions.csproj" />
    <ProjectReference Include="..\..\..\Common\Results\Common.Results\Common.Results.csproj" />
    <ProjectReference Include="..\Inventory.Domain\Inventory.Core.Domain.csproj" />
  </ItemGroup>
</Project>
